"""Pipeline executor: bridges task execution with the ingestion pipeline.

Takes a ``BatchContext`` from the scheduler, groups tasks by their logical
identity, fetches data via akshare, aggregates DataFrames, and feeds each
group through ``Pipeline.run_one_batch()``.

Usage::

    from datetime import date
    from akshare_data.ingestion.scheduler import Scheduler
    from akshare_data.ingestion.pipeline_executor import PipelineExecutor

    scheduler = Scheduler()
    batch = scheduler.generate_batch(extract_date=date.today())

    executor = PipelineExecutor()
    results = executor.execute_batch(batch)
"""

from __future__ import annotations

import inspect
import logging
import time
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import date
from typing import Any, Dict, List, Optional

import pandas as pd

from akshare_data.ingestion.models import BatchContext, ExtractTask
from akshare_data.ingestion.pipeline import Pipeline, PipelineResult

logger = logging.getLogger("akshare_data.pipeline_executor")


# ---------------------------------------------------------------------------
# PipelineExecutorResult
# ---------------------------------------------------------------------------


@dataclass
class PipelineExecutorResult:
    """Aggregated outcome of ``PipelineExecutor.execute_batch()``.

    Attributes
    ----------
    batch_id : str
        The original batch ID from the scheduler.
    pipeline_results : list[PipelineResult]
        One result per task group that was processed.
    total_tasks : int
        Total number of tasks in the input batch.
    total_groups : int
        Number of task groups (unique dataset/source/interface/date combos).
    total_published : int
        How many groups were successfully published.
    total_errors : int
        Total number of errors across all pipeline results.
    duration_ms : float
        Wall-clock time for the entire batch execution.
    """

    batch_id: str
    pipeline_results: List[PipelineResult] = field(default_factory=list)
    total_tasks: int = 0
    total_groups: int = 0
    total_published: int = 0
    total_errors: int = 0
    duration_ms: float = 0.0


# ---------------------------------------------------------------------------
# PipelineExecutor
# ---------------------------------------------------------------------------


class PipelineExecutor:
    """Executes a ``BatchContext`` through the ingestion pipeline.

    Groups tasks by ``(dataset, source_name, interface_name, extract_date)``,
    fetches data for each group, aggregates the DataFrames, and runs them
    through ``Pipeline.run_one_batch()``.

    Parameters
    ----------
    pipeline : Pipeline, optional
        Pre-configured pipeline instance.  If not provided, a default
        Pipeline is created with standard directory layout.
    """

    def __init__(
        self,
        pipeline: Optional[Pipeline] = None,
    ) -> None:
        self._pipeline = pipeline or Pipeline()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def execute_batch(
        self,
        batch: BatchContext,
    ) -> PipelineExecutorResult:
        """Execute all tasks in a batch through the ingestion pipeline.

        Steps
        -----
        1. Group tasks by ``(dataset, source_name, interface_name, extract_date)``.
        2. For each group, fetch data via akshare and aggregate DataFrames.
        3. Call ``Pipeline.run_one_batch()`` for each group.
        4. Return aggregated ``PipelineExecutorResult``.

        Parameters
        ----------
        batch : BatchContext
            Batch of tasks generated by the scheduler or backfill consumer.

        Returns
        -------
        PipelineExecutorResult
        """
        t_start = time.monotonic()

        groups = self._group_tasks(batch.tasks)
        logger.info(
            "PipelineExecutor: batch=%s tasks=%d groups=%d",
            batch.batch_id,
            len(batch.tasks),
            len(groups),
        )

        results: List[PipelineResult] = []
        for group_key, tasks in groups.items():
            dataset, source_name, interface_name, extract_date = group_key
            task = tasks[0]

            df = self._fetch_group(tasks, source_name, interface_name)
            if df is None or df.empty:
                logger.warning(
                    "No data for group: dataset=%s interface=%s date=%s",
                    dataset,
                    interface_name,
                    extract_date,
                )
                continue

            pipeline_result = self._run_pipeline(
                df=df,
                task=task,
                dataset=dataset,
                source_name=source_name,
                interface_name=interface_name,
                extract_date=extract_date,
                batch_id=batch.batch_id,
            )
            results.append(pipeline_result)

        duration_ms = (time.monotonic() - t_start) * 1000
        total_published = sum(1 for r in results if r.published)
        total_errors = sum(len(r.errors) for r in results)

        return PipelineExecutorResult(
            batch_id=batch.batch_id,
            pipeline_results=results,
            total_tasks=len(batch.tasks),
            total_groups=len(groups),
            total_published=total_published,
            total_errors=total_errors,
            duration_ms=duration_ms,
        )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _group_tasks(
        self, tasks: List[ExtractTask]
    ) -> Dict[tuple, List[ExtractTask]]:
        groups: Dict[tuple, List[ExtractTask]] = defaultdict(list)
        for task in tasks:
            key = (
                task.dataset,
                task.source_name,
                task.interface_name,
                task.extract_date,
            )
            groups[key].append(task)

        for key in groups:
            groups[key].sort(key=lambda t: t.priority)
        return dict(groups)

    def _fetch_group(
        self,
        tasks: List[ExtractTask],
        source_name: str,
        interface_name: str,
    ) -> Optional[pd.DataFrame]:
        frames: List[pd.DataFrame] = []
        for task in tasks:
            df = self._fetch_one(source_name, interface_name, task.params)
            if df is not None and not df.empty:
                frames.append(df)

        if not frames:
            return None
        if len(frames) == 1:
            return frames[0]
        return pd.concat(frames, ignore_index=True)

    def _fetch_one(
        self,
        source_name: str,
        interface_name: str,
        params: Dict[str, Any],
    ) -> Optional[pd.DataFrame]:
        kwargs = self._prepare_kwargs(interface_name, params)
        if not kwargs:
            logger.warning("No valid kwargs for %s, skipping fetch", interface_name)
            return None

        try:
            import akshare as ak

            func = getattr(ak, interface_name, None)
            if func is None:
                logger.error("akshare function %s not found", interface_name)
                return None
            return func(**kwargs)
        except Exception as exc:
            logger.error("Fetch failed for %s: %s", interface_name, exc)
            return None

    def _prepare_kwargs(
        self,
        interface_name: str,
        params: Dict[str, Any],
    ) -> Dict[str, Any]:
        import akshare as ak

        func = getattr(ak, interface_name, None)
        if func is None:
            return dict(params)

        try:
            sig = inspect.signature(func)
            param_names = set(sig.parameters.keys())
        except (ValueError, TypeError):
            return dict(params)

        kwargs: Dict[str, Any] = {}
        for key, value in params.items():
            if key not in param_names:
                continue
            if isinstance(value, str) and key in (
                "start_date",
                "end_date",
                "date",
                "start",
                "end",
                "begin",
                "finish",
            ):
                kwargs[key] = value.replace("-", "")
            else:
                kwargs[key] = value
        return kwargs

    def _run_pipeline(
        self,
        df: pd.DataFrame,
        task: ExtractTask,
        *,
        dataset: str,
        source_name: str,
        interface_name: str,
        extract_date: date,
        batch_id: str,
    ) -> PipelineResult:
        partition_key = self._infer_partition_key(df)
        primary_key = self._infer_primary_key(dataset)

        return self._pipeline.run_one_batch(
            df,
            dataset=dataset,
            domain=task.domain,
            source_name=source_name,
            interface_name=interface_name,
            extract_date=extract_date,
            partition_key=partition_key,
            primary_key=primary_key,
            batch_id=batch_id,
        )

    def _infer_partition_key(self, df: pd.DataFrame) -> str:
        for col in ("trade_date", "date", "report_date", "datetime"):
            if col in df.columns:
                return col
        return "trade_date"

    def _infer_primary_key(self, dataset: str) -> List[str]:
        defaults: Dict[str, List[str]] = {
            "market_quote_daily": ["security_id", "trade_date", "adjust_type"],
            "etf_daily": ["fund_code", "trade_date"],
            "index_daily": ["index_code", "trade_date"],
            "financial_indicator": ["symbol", "report_date"],
        }
        if dataset in defaults:
            return defaults[dataset]
        return ["symbol", "trade_date"]
